
require("./SmartDataVisualization.module.css");
const styles = {
  container: 'container_f8a41f4f',
  webPartHeader: 'webPartHeader_f8a41f4f',
  webPartHeaderText: 'webPartHeaderText_f8a41f4f',
  editPanel: 'editPanel_f8a41f4f',
  sectionHeader: 'sectionHeader_f8a41f4f',
  sourceTypeGrid: 'sourceTypeGrid_f8a41f4f',
  sourceTypeCard: 'sourceTypeCard_f8a41f4f',
  selected: 'selected_f8a41f4f',
  icon: 'icon_f8a41f4f',
  label: 'label_f8a41f4f',
  fieldRow: 'fieldRow_f8a41f4f',
  fieldGroup: 'fieldGroup_f8a41f4f',
  helpText: 'helpText_f8a41f4f',
  buttonRow: 'buttonRow_f8a41f4f',
  primaryButton: 'primaryButton_f8a41f4f',
  secondaryButton: 'secondaryButton_f8a41f4f',
  errorMessage: 'errorMessage_f8a41f4f',
  successMessage: 'successMessage_f8a41f4f',
  warningMessage: 'warningMessage_f8a41f4f',
  loadedFileBanner: 'loadedFileBanner_f8a41f4f',
  loadedFileIcon: 'loadedFileIcon_f8a41f4f',
  loadedFileInfo: 'loadedFileInfo_f8a41f4f',
  loadedFileRows: 'loadedFileRows_f8a41f4f',
  loadedFileActions: 'loadedFileActions_f8a41f4f',
  noDataMessage: 'noDataMessage_f8a41f4f',
  chartWrapper: 'chartWrapper_f8a41f4f',
  multiSelect: 'multiSelect_f8a41f4f',
  tableWrapper: 'tableWrapper_f8a41f4f',
  dataTable: 'dataTable_f8a41f4f',
  paginationBar: 'paginationBar_f8a41f4f',
  exportBar: 'exportBar_f8a41f4f',
  exportLabel: 'exportLabel_f8a41f4f',
  exportButton: 'exportButton_f8a41f4f',
  exportIcon: 'exportIcon_f8a41f4f',
  refreshButton: 'refreshButton_f8a41f4f',
  spinnerWrapper: 'spinnerWrapper_f8a41f4f',
  spinnerRing: 'spinnerRing_f8a41f4f',
  spin: 'spin_f8a41f4f',
  colorSwatch: 'colorSwatch_f8a41f4f',
  dataControlsPanel: 'dataControlsPanel_f8a41f4f',
  configToggleRow: 'configToggleRow_f8a41f4f',
  configToggleButton: 'configToggleButton_f8a41f4f',
  configToggleBadge: 'configToggleBadge_f8a41f4f',
  kpiTile: 'kpiTile_f8a41f4f',
  kpiTitle: 'kpiTitle_f8a41f4f',
  kpiValue: 'kpiValue_f8a41f4f',
  kpiSubLabel: 'kpiSubLabel_f8a41f4f',
  viewerFilterBar: 'viewerFilterBar_f8a41f4f',
  viewerFilterLabel: 'viewerFilterLabel_f8a41f4f',
  drillBreadcrumb: 'drillBreadcrumb_f8a41f4f',
  breadcrumbLink: 'breadcrumbLink_f8a41f4f',
  breadcrumbSeparator: 'breadcrumbSeparator_f8a41f4f',
  breadcrumbCurrent: 'breadcrumbCurrent_f8a41f4f',
  detailChip: 'detailChip_f8a41f4f',
  bookmarkList: 'bookmarkList_f8a41f4f',
  bookmarkName: 'bookmarkName_f8a41f4f'
};

export default styles;
