define([], function() {
  return {
    "PropertyPaneDescription": "Configure your data visualization",
    // Header
    "HeaderGroupName": "Header",
    "WebPartHeaderFieldLabel": "Header Text",
    "WebPartHeaderPlaceholder": "e.g. Sales Dashboard",
    "ShowWebPartHeaderFieldLabel": "Show Header",
    // Chart Settings group
    "ChartSettingsGroupName": "Chart Settings",
    "ChartTitleFieldLabel": "Chart Title",
    "ChartTypeFieldLabel": "Chart Type",
    "LegendPositionFieldLabel": "Legend Position",
    "ChartHeightFieldLabel": "Chart Height (px)",
    "ShowLegendFieldLabel": "Show Legend",
    "StackedFieldLabel": "Stacked (Bar/Line)",
    "ShowDataTableFieldLabel": "Show Data Table",
    "ShowExportBarFieldLabel": "Show Export Bar",
    "XAxisLabelFieldLabel": "X Axis Label",
    "XAxisPlaceholder": "e.g. Month",
    "YAxisLabelFieldLabel": "Y Axis Label",
    "YAxisPlaceholder": "e.g. Sales ($)",
    // Chart type group headers
    "ChartGroupStandard": "Standard Charts",
    "ChartGroupSpecialized": "Specialized Charts",
    // Chart type options
    "ChartTypeBarLabel": "Bar Chart (Vertical)",
    "ChartTypeHorizontalBarLabel": "Bar Chart (Horizontal)",
    "ChartTypeLineLabel": "Line Chart",
    "ChartTypeAreaLabel": "Area Chart",
    "ChartTypeScatterLabel": "Scatter Plot",
    "ChartTypePieLabel": "Pie Chart",
    "ChartTypeDoughnutLabel": "Doughnut Chart",
    "ChartTypeBubbleLabel": "Bubble Chart",
    "ChartTypeRadarLabel": "Radar Chart",
    "ChartTypeKpiLabel": "KPI Tile",
    "ChartTypeHistogramLabel": "Histogram",
    "ChartTypeWaterfallLabel": "Waterfall Chart",
    "ChartTypeBoxplotLabel": "Box Plot",
    "ChartTypeViolinLabel": "Violin Plot",
    "ChartTypeBeforeAfterLabel": "Before-After Plot",
    "ChartTypeTreemapLabel": "Treemap",
    "ChartTypeHeatmapLabel": "Heatmap",
    "HistogramBinsFieldLabel": "Histogram Bins",
    "AppearancePageDescription": "Colors, labels, and axes",
    "AdvancedPageDescription": "Analytics, reference lines, interactivity, and data refresh",
    "AdvancedToggleGroupName": "Advanced",
    "ShowAdvancedOptionsFieldLabel": "Show Advanced Options",
    // Legend position options
    "LegendTopLabel": "Top",
    "LegendBottomLabel": "Bottom",
    "LegendLeftLabel": "Left",
    "LegendRightLabel": "Right",
    // Colors group
    "ColorsGroupName": "Colors",
    "ColorPaletteFieldLabel": "Color Palette",
    "PaletteOfficeLabel": "Office (Default)",
    "PaletteVibrantLabel": "Vibrant",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monochrome",
    "PaletteTrafficLightLabel": "Traffic Light",
    "PaletteWarmLabel": "Warm",
    "PaletteCoolLabel": "Cool",
    // Data Labels group
    "DataLabelsGroupName": "Data Labels & Formatting",
    "ShowDataLabelsFieldLabel": "Show Data Labels",
    "ValuePrefixFieldLabel": "Value Prefix",
    "ValuePrefixPlaceholder": "e.g. $",
    "ValueSuffixFieldLabel": "Value Suffix",
    "ValueSuffixPlaceholder": "e.g. %",
    "ValueDecimalsFieldLabel": "Decimal Places",
    "AbbreviateNumbersFieldLabel": "Abbreviate Numbers (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Axes & Grid",
    "YAxisMinFieldLabel": "Y Axis Minimum",
    "YAxisMaxFieldLabel": "Y Axis Maximum",
    "AutoPlaceholder": "Auto",
    "NumericValidationError": "Enter a number, or leave blank for automatic.",
    "LogScaleFieldLabel": "Logarithmic Scale (Y)",
    "LogScaleXFieldLabel": "Logarithmic Scale (X)",
    "StepLineFieldLabel": "Step Interpolation",
    "ShowGridLinesFieldLabel": "Show Grid Lines",
    "XLabelRotationFieldLabel": "X Label Rotation (degrees)",
    // Axes — X axis type
    "XAxisTypeFieldLabel": "X Axis Type",
    "XAxisTypeAuto": "Auto-detect",
    "XAxisTypeCategory": "Category",
    "XAxisTypeTime": "Time (dates)",
    // Analytics group
    "AnalyticsGroupName": "Analytics",
    "TrendlineFieldLabel": "Trendline",
    "TrendlineNone": "None",
    "TrendlineLinear": "Linear",
    "TrendlineMovingAverage": "Moving Average",
    "TrendWindowFieldLabel": "Moving Average Window",
    "TrendSuffix": " (trend)",
    "ForecastPeriodsFieldLabel": "Forecast Periods (linear trendline)",
    // Reference line
    "ReferenceLineGroupName": "Reference Line",
    "ReferenceLineTypeFieldLabel": "Reference Line",
    "ReferenceLineValueFieldLabel": "Fixed Value",
    "ReferenceLineColorFieldLabel": "Line Color (hex)",
    "RefLineFixed": "Fixed value",
    "RefLineMean": "Mean",
    "RefLineMedian": "Median",
    // Dual Y axis group
    "DualAxisGroupName": "Dual Y Axis",
    "Y2ColumnsFieldLabel": "Right-axis series (comma-separated column names)",
    "Y2ColumnsPlaceholder": "e.g. Margin,Growth",
    "Y2AxisLabelFieldLabel": "Right axis label",
    // Error bars group
    "ErrorBarsGroupName": "Error Bars",
    "ErrorBarTypeFieldLabel": "Error Bar Type",
    "ErrorBarTypeNone": "None",
    "ErrorBarTypeCustom": "Custom column (±)",
    "ErrorBarTypeSd": "Std Dev (computed)",
    "ErrorBarTypeSem": "Std Error of Mean (computed)",
    "ErrorBarColumnFieldLabel": "Error value column",
    // Significance annotations group
    "SignificanceGroupName": "Significance Brackets",
    "SignificancePairsFieldLabel": "Bracket pairs",
    "SignificancePairsPlaceholder": "[{\"col1\":\"A\",\"col2\":\"B\",\"label\":\"*\"}]",
    "SignificancePairsHelp": "JSON array: [{\"col1\":\"Category A\",\"col2\":\"Category B\",\"label\":\"*\"}]",
    // Interactivity
    "InteractivityGroupName": "Interactivity",
    "ShowViewerFiltersFieldLabel": "Show Filters to Viewers",
    "DetailsOnDemandFieldLabel": "Details on Demand (click chart for rows)",
    "ShowDataPointsFieldLabel": "Overlay Data Points on Bars",
    "ShowBubbleSizeLegendFieldLabel": "Show Bubble Size Legend",
    "ViewerFilterLabel": "Filter:",
    "ViewerFilterColumnAria": "Filter column",
    "ViewerFilterValueAria": "Filter value",
    "DrillAllLabel": "All",
    "DetailsChipLabel": "Details: {0} ({1} rows)",
    // KPI
    "KpiSubLabel": "{0} • {1} rows",
    // Conditional formatting group
    "ConditionalGroupName": "Conditional Formatting",
    "ThresholdValueFieldLabel": "Threshold Value",
    "ThresholdValuePlaceholder": "Off",
    "ThresholdDirectionFieldLabel": "Highlight Values",
    "ThresholdBelow": "Below threshold",
    "ThresholdAbove": "Above threshold",
    "ThresholdColorFieldLabel": "Highlight Color (hex)",
    // Data & refresh group
    "DataRefreshGroupName": "Data & Refresh",
    "RefreshIntervalFieldLabel": "Auto-Refresh Interval (minutes, 0 = off)",
    "CacheMinutesFieldLabel": "Cache API Results (minutes, 0 = off)",
    // Dynamic data
    "DynamicDataCategoryLabel": "Selected category",
    "DynamicDataValueLabel": "Selected value",
    "DynamicDataSeriesLabel": "Selected series",
    // Legacy / unused
    "DataSourceGroupName": "Data Source",
    // Main component
    "HideDataSourceButton": "▲ Hide Data Source",
    "ConfigureDataSourceButton": "▼ Configure Data Source",
    "RowsLoadedBadge": "✓ {0} rows loaded",
    "ReadModeLoadError": "Could not load data: {0}. Switch to Edit mode to reconfigure the data source.",
    "RefreshDataButton": "↻ Refresh Data",
    "RefreshingLabel": "Refreshing…",
    "RefreshDataTitle": "Reload data from the configured source",
    // Chart renderer
    "NoDataMessage": "No data loaded yet. Configure your data source above and click Load Data.",
    "SelectMappingsMessage": "Data loaded ({0} rows). Please select column mappings above to display the chart.",
    "ChartRenderErrorLabel": "Chart rendering error: {0}",
    "UnsupportedChartTypeLabel": "Unsupported chart type: {0}",
    "ChartAriaLabel": "Data visualization chart",
    "ScatterNumericWarning": "Scatter and bubble charts need numeric values. The column \"{0}\" has no numeric data — choose a different column in the mapping above.",
    // Data source panel
    "DataSourceSectionHeader": "Data Source",
    "SourceUploadLabel": "Upload File",
    "SourceSharePointListLabel": "SharePoint List",
    "SourceSharePointFileLabel": "SharePoint File",
    "SourceRestApiLabel": "REST API",
    "SourceGraphApiLabel": "Microsoft Graph",
    "GraphPathLabel": "Graph API Path",
    "GraphPathHelp": "Relative Microsoft Graph path, e.g. /me/memberOf or /reports/getTeamsUserActivityUserCounts(period='D7'). This source requires Graph permissions approved by an administrator — all other data sources work without them.",
    "SheetNameLabel": "Excel Sheet",
    "DelimiterLabel": "Delimiter",
    "DelimiterAutoDetect": "Auto-detect",
    "DelimiterComma": "Comma (,)",
    "DelimiterTab": "Tab",
    "DelimiterSemicolon": "Semicolon (;)",
    "DelimiterPipe": "Pipe (|)",
    "SiteUrlLabel": "Site URL (optional)",
    "SiteUrlHelp": "Leave blank to use the current site.",
    "ListNameLabel": "List Name",
    "LoadingListsLabel": "— Loading lists…",
    "SelectListPlaceholder": "— Select a list —",
    "EnterListNamePlaceholder": "Enter list name",
    "ListNameExamplePlaceholder": "e.g. Sales Data",
    "ListDiscoveryError": "Could not load lists — enter name manually below.",
    "FileUrlLabel": "File URL (CSV/TSV/Excel in SharePoint)",
    "FileUrlHelp": "Full URL to a file in a document library.",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "Data Path (optional)",
    "DataPathHelp": "Dot-separated path to the array in the JSON response. Leave blank if the root is an array. For SharePoint REST API use \"value\".",
    "UploadHelp": "Upload a CSV, TSV, or Excel (.xlsx, .xls) file.",
    "LoadedFileRowsLabel": "— {0} rows",
    "ChangeFileButton": "Change File…",
    "ClearButton": "Clear",
    "ChooseFileButton": "Choose File…",
    "LoadDataButton": "Load Data",
    "LoadingLabel": "Loading…",
    "ErrorSelectListName": "Please select or enter a list name.",
    "ErrorEnterFileUrl": "Please enter a file URL.",
    "ErrorEnterUrl": "Please enter a URL.",
    "ErrorLoadList": "Failed to load SharePoint list: {0}",
    "ErrorLoadFile": "Failed to load file: {0}",
    "ErrorFetchData": "Failed to fetch data: {0}",
    "ErrorUnsupportedFileType": "Unsupported file type. Please upload a .csv, .tsv, .xlsx, or .xls file.",
    "ErrorReadFile": "Failed to read file",
    "ErrorParseFile": "Failed to parse file",
    "LoadedRowsColumns": "Loaded {0} rows with {1} columns.",
    "LoadedRowsColumnsPersist": "Loaded {0} rows with {1} columns. Data will persist when you leave the page.",
    "SizeWarning": "Dataset ({0}KB) exceeds the 200KB persistence limit. The chart will show data this session but will clear on page reload. For large files, upload to a SharePoint library and use the SharePoint File source.",
    "ListTruncatedWarning": "This list has {0} or more items; only the first {0} were loaded.",
    // Column mapper
    "ColumnMappingSectionHeader": "Column Mapping",
    "CategoryColumnLabel": "Category Column (X / Labels)",
    "LabelColumnLabel": "Label Column",
    "XAxisColumnLabel": "X Axis Column",
    "ValueColumnLabel": "Value Column",
    "YAxisColumnLabel": "Y Axis Column",
    "YAxisColumnsLabel": "Y Axis Column(s)",
    "YAxisColumnsHelp": "(select one or more; click swatch to set color)",
    "SelectColumnPlaceholder": "— Select column —",
    "ScatterLabelColumnLabel": "Point Label",
    "SizeColumnLabel":"Size / Radius Column",
    "NoSizeColumnOption": "— None (fixed size) —",
    "SeriesColorTitle": "Color for {0}",
    "SeriesTypeTitle": "Chart type for {0}",
    "SeriesTypeDefault": "Default",
    "SeriesTypeBar": "Bar",
    "SeriesTypeLine": "Line",
    "HistogramColumnLabel": "Column to Bin (numeric)",
    "TreemapGroupLabel": "Group / Label Column",
    "HeatmapColumnLabel": "Column (X) Category",
    "HeatmapRowLabel": "Row (Y) Category",
    // Advanced options panel
    "AdvancedOptionsClosed": "▼ Advanced Options",
    "AdvancedOptionsOpen": "▲ Advanced Options",
    "ColorByLabel": "Color by Column",
    "ColorByHelp": "Color points by category instead of by series.",
    "TooltipColumnsLabel": "Tooltip Columns",
    "TooltipColumnsHelp": "(extra columns shown when hovering a data point)",
    "DrillLevelLabel": "Drill Level {0}",
    "DrillDownHelp": "Define a column hierarchy to enable click-to-drill (e.g. Region → Country → City). Values are aggregated at each level.",
    "BookmarksLabel": "Bookmarks",
    "BookmarkNameLabel": "Bookmark Name",
    "BookmarkNamePlaceholder": "e.g. Top 10 by Region",
    "SaveBookmarkButton": "Save Current View",
    "ApplyBookmarkButton": "Apply",
    "DeleteBookmarkButton": "Delete",
    "ApplyBookmarkPlaceholder": "— Apply a bookmark —",
    // Data controls
    "DataControlsSectionHeader": "Data Controls",
    "SortByColumnLabel": "Sort by Column",
    "NoneOption": "— None —",
    "SortDirectionLabel": "Sort Direction",
    "AscendingOption": "Ascending",
    "DescendingOption": "Descending",
    "RowLimitLabel": "Row Limit (0 = all)",
    "FilterColumnLabel": "Filter Column",
    "FilterContainsLabel": "Filter: contains",
    "FilterValuePlaceholder": "Filter value…",
    "GroupByLabel": "Group by Column",
    "AggregationLabel": "Aggregation",
    "GroupByHelp": "Numeric columns are aggregated per group. Count adds a \"Count\" column.",
    "AggNone": "None",
    "AggSum": "Sum",
    "AggAvg": "Average",
    "AggCount": "Count",
    "AggMin": "Min",
    "AggMax": "Max",
    // Data table
    "DataTableHeader": "Data Table ({0} rows)",
    "PrevPageButton": "← Prev",
    "NextPageButton": "Next →",
    "PageOfLabel": "Page {0} of {1}",
    // Export bar
    "ExportLabel": "Export:",
    "ExportPngTitle": "Download chart as PNG image",
    "ExportJpegTitle": "Download chart as JPEG image",
    "ExportCsvTitle": "Download data as CSV",
    "ExportExcelTitle": "Download data as Excel workbook"
  }
});
