define([], function() {
  return {
    "PropertyPaneDescription": "Configure your data visualization",
    // Header
    "HeaderGroupName": "Header",
    "WebPartHeaderFieldLabel": "Header Text",
    "WebPartHeaderPlaceholder": "e.g. Sales Dashboard",
    "ShowWebPartHeaderFieldLabel": "Show Header",
    // Chart Settings group
    "ChartSettingsGroupName": "Chart Settings",
    "ChartTitleFieldLabel": "Chart Title",
    "ChartTypeFieldLabel": "Chart Type",
    "LegendPositionFieldLabel": "Legend Position",
    "ChartHeightFieldLabel": "Chart Height (px)",
    "ShowLegendFieldLabel": "Show Legend",
    "StackedFieldLabel": "Stacked (Bar/Line)",
    "ShowDataTableFieldLabel": "Show Data Table",
    "ShowExportBarFieldLabel": "Show Export Bar",
    "XAxisLabelFieldLabel": "X Axis Label",
    "XAxisPlaceholder": "e.g. Month",
    "YAxisLabelFieldLabel": "Y Axis Label",
    "YAxisPlaceholder": "e.g. Sales ($)",
    // Chart type options
    "ChartTypeBarLabel": "Bar Chart (Vertical)",
    "ChartTypeHorizontalBarLabel": "Bar Chart (Horizontal)",
    "ChartTypeLineLabel": "Line Chart",
    "ChartTypeAreaLabel": "Area Chart",
    "ChartTypeScatterLabel": "Scatter Plot",
    "ChartTypePieLabel": "Pie Chart",
    "ChartTypeDoughnutLabel": "Doughnut Chart",
    "ChartTypeBubbleLabel": "Bubble Chart",
    "ChartTypeRadarLabel": "Radar Chart",
    // Legend position options
    "LegendTopLabel": "Top",
    "LegendBottomLabel": "Bottom",
    "LegendLeftLabel": "Left",
    "LegendRightLabel": "Right",
    // Colors group
    "ColorsGroupName": "Colors",
    "ColorPaletteFieldLabel": "Color Palette",
    "PaletteOfficeLabel": "Office (Default)",
    "PaletteVibrantLabel": "Vibrant",
    "PalettePastelLabel": "Pastel",
    "PaletteMonochromeLabel": "Monochrome",
    "PaletteTrafficLightLabel": "Traffic Light",
    "PaletteWarmLabel": "Warm",
    "PaletteCoolLabel": "Cool",
    // Data Labels group
    "DataLabelsGroupName": "Data Labels & Formatting",
    "ShowDataLabelsFieldLabel": "Show Data Labels",
    "ValuePrefixFieldLabel": "Value Prefix",
    "ValuePrefixPlaceholder": "e.g. $",
    "ValueSuffixFieldLabel": "Value Suffix",
    "ValueSuffixPlaceholder": "e.g. %",
    "ValueDecimalsFieldLabel": "Decimal Places",
    "AbbreviateNumbersFieldLabel": "Abbreviate Numbers (K/M)",
    // Axes & Grid group
    "AxesGridGroupName": "Axes & Grid",
    "YAxisMinFieldLabel": "Y Axis Minimum",
    "YAxisMaxFieldLabel": "Y Axis Maximum",
    "AutoPlaceholder": "Auto",
    "NumericValidationError": "Enter a number, or leave blank for automatic.",
    "LogScaleFieldLabel": "Logarithmic Scale",
    "ShowGridLinesFieldLabel": "Show Grid Lines",
    "XLabelRotationFieldLabel": "X Label Rotation (degrees)",
    // Legacy / unused
    "DataSourceGroupName": "Data Source",
    // Main component
    "HideDataSourceButton": "▲ Hide Data Source",
    "ConfigureDataSourceButton": "▼ Configure Data Source",
    "RowsLoadedBadge": "✓ {0} rows loaded",
    "ReadModeLoadError": "Could not load data: {0}. Switch to Edit mode to reconfigure the data source.",
    "RefreshDataButton": "↻ Refresh Data",
    "RefreshingLabel": "Refreshing…",
    "RefreshDataTitle": "Reload data from the configured source",
    // Chart renderer
    "NoDataMessage": "No data loaded yet. Configure your data source above and click Load Data.",
    "SelectMappingsMessage": "Data loaded ({0} rows). Please select column mappings above to display the chart.",
    "ChartRenderErrorLabel": "Chart rendering error: {0}",
    "UnsupportedChartTypeLabel": "Unsupported chart type: {0}",
    "ChartAriaLabel": "Data visualization chart",
    // Data source panel
    "DataSourceSectionHeader": "Data Source",
    "SourceUploadLabel": "Upload File",
    "SourceSharePointListLabel": "SharePoint List",
    "SourceSharePointFileLabel": "SharePoint File",
    "SourceRestApiLabel": "REST API",
    "DelimiterLabel": "Delimiter",
    "DelimiterAutoDetect": "Auto-detect",
    "DelimiterComma": "Comma (,)",
    "DelimiterTab": "Tab",
    "DelimiterSemicolon": "Semicolon (;)",
    "DelimiterPipe": "Pipe (|)",
    "SiteUrlLabel": "Site URL (optional)",
    "SiteUrlHelp": "Leave blank to use the current site.",
    "ListNameLabel": "List Name",
    "LoadingListsLabel": "— Loading lists…",
    "SelectListPlaceholder": "— Select a list —",
    "EnterListNamePlaceholder": "Enter list name",
    "ListNameExamplePlaceholder": "e.g. Sales Data",
    "ListDiscoveryError": "Could not load lists — enter name manually below.",
    "FileUrlLabel": "File URL (CSV/TSV/Excel in SharePoint)",
    "FileUrlHelp": "Full URL to a file in a document library.",
    "ApiUrlLabel": "API URL",
    "DataPathLabel": "Data Path (optional)",
    "DataPathHelp": "Dot-separated path to the array in the JSON response. Leave blank if the root is an array. For SharePoint REST API use \"value\".",
    "UploadHelp": "Upload a CSV, TSV, or Excel (.xlsx, .xls) file.",
    "LoadedFileRowsLabel": "— {0} rows",
    "ChangeFileButton": "Change File…",
    "ClearButton": "Clear",
    "ChooseFileButton": "Choose File…",
    "LoadDataButton": "Load Data",
    "LoadingLabel": "Loading…",
    "ErrorSelectListName": "Please select or enter a list name.",
    "ErrorEnterFileUrl": "Please enter a file URL.",
    "ErrorEnterUrl": "Please enter a URL.",
    "ErrorLoadList": "Failed to load SharePoint list: {0}",
    "ErrorLoadFile": "Failed to load file: {0}",
    "ErrorFetchData": "Failed to fetch data: {0}",
    "ErrorUnsupportedFileType": "Unsupported file type. Please upload a .csv, .tsv, .xlsx, or .xls file.",
    "ErrorReadFile": "Failed to read file",
    "ErrorParseFile": "Failed to parse file",
    "LoadedRowsColumns": "Loaded {0} rows with {1} columns.",
    "LoadedRowsColumnsPersist": "Loaded {0} rows with {1} columns. Data will persist when you leave the page.",
    "SizeWarning": "Dataset ({0}KB) exceeds the 200KB persistence limit. The chart will show data this session but will clear on page reload. For large files, upload to a SharePoint library and use the SharePoint File source.",
    "ListTruncatedWarning": "This list has {0} or more items; only the first {0} were loaded.",
    // Column mapper
    "ColumnMappingSectionHeader": "Column Mapping",
    "CategoryColumnLabel": "Category Column (X / Labels)",
    "LabelColumnLabel": "Label Column",
    "XAxisColumnLabel": "X Axis Column",
    "ValueColumnLabel": "Value Column",
    "YAxisColumnLabel": "Y Axis Column",
    "YAxisColumnsLabel": "Y Axis Column(s)",
    "YAxisColumnsHelp": "(select one or more; click swatch to set color)",
    "SelectColumnPlaceholder": "— Select column —",
    "SizeColumnLabel": "Size / Radius Column",
    "NoSizeColumnOption": "— None (fixed size) —",
    "SeriesColorTitle": "Color for {0}",
    // Data controls
    "DataControlsSectionHeader": "Data Controls",
    "SortByColumnLabel": "Sort by Column",
    "NoneOption": "— None —",
    "SortDirectionLabel": "Sort Direction",
    "AscendingOption": "Ascending",
    "DescendingOption": "Descending",
    "RowLimitLabel": "Row Limit (0 = all)",
    "FilterColumnLabel": "Filter Column",
    "FilterContainsLabel": "Filter: contains",
    "FilterValuePlaceholder": "Filter value…",
    // Data table
    "DataTableHeader": "Data Table ({0} rows)",
    "PrevPageButton": "← Prev",
    "NextPageButton": "Next →",
    "PageOfLabel": "Page {0} of {1}",
    // Export bar
    "ExportLabel": "Export:",
    "ExportPngTitle": "Download chart as PNG image",
    "ExportJpegTitle": "Download chart as JPEG image",
    "ExportCsvTitle": "Download data as CSV",
    "ExportExcelTitle": "Download data as Excel workbook"
  }
});
